version: "3.8"

services:
    haciendola-backend:
        build: .
        ports:
            - "3006:3006"
        environment:
            DB_PASSWORD: "haciendola-admin"
            DB_USERNAME: "root"
            DB_HOST: "db"
            DB_PORT: 3306
            JWT_SECRET: "supersecret"
        depends_on:
            - db
        restart: on-failure # Restart policy
        networks:
            - haciendola-network

    db:
        image: mysql:8.4
        container_name: haciendola-mysql
        environment:
            MYSQL_ROOT_PASSWORD: "haciendola-admin"
            MYSQL_DATABASE: "sys"
        networks:
            - haciendola-network
networks:
    haciendola-network:
        external: true
